No longer filter chain accounts and revert on quote pay creation
legend-hq/legend-scripts pull request #40
Opened 2024-12-13 22:50 UTC by mykelp

2024-12-13 22:53 UTC, hayesgm approved these changes

2024-12-16 16:54 UTC, kevincheng96 requested changes
LGTM, though you'll need to modify the tests to pass in Quotes for the previously filtered-out chains since it's reverting with `MaxCostMissingForChain` now. Either that, or just make it so missing quotes don't revert.

2024-12-17 00:19 UTC, hayesgm approved these changes

2024-12-17 00:36 UTC, mykelp commented
> LGTM, though you'll need to modify the tests to pass in Quotes for the previously filtered-out chains since it's reverting with `MaxCostMissingForChain` now. Either that, or just make it so missing quotes don't revert.

Updated tests to pass quotes for chains that have balances. The quote checks now only care to look at chains that have balances on it, otherwise it reverts with`IMPOSSIBLE_TO_CONSTRUCT`

2024-12-17 00:37 UTC, merged